### ISSUE TITLE
Is it using AWS older version and needs to bee upgraded?

### ISSUE THREAD

**Issue by seamaster101** [sbender9/signalk-cloud#21]
@sbender9 please help...
I have issue starting the service. There appears to be couples of issues. one of them refers to AWS SDK for JavaScript (v2) needed to be upgraded 
Is that something that could be causing this issue?
Please check the log below 

`Apr 21 22:51:26 Could not parse security config
Apr 21 22:51:27 ENOENT: no such file or directory, open '/data/conf/signalk/security.json'
Apr 21 22:51:38 signalk-cloud failed to start: Package subpath './v4' is not defined by "exports" in /data/conf/signalk/node_modules/uuid/package.json
Apr 21 22:51:38 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /data/conf/signalk/node_modules/uuid/package.json at throwExportsNotFound (internal/modules/esm/resolve.js:299:9) at packageExportsResolve (internal/modules/esm/resolve.js:522:3) at resolveExports (internal/modules/cjs/loader.js:449:36) at Function.Module._findPath (internal/modules/cjs/loader.js:489:31) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27) at Function.Module._load (internal/modules/cjs/loader.js:745:27) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at Object.<anonymous> (/data/conf/signalk/node_modules/signalk-cloud/index.js:5:16) at Module._compile (internal/modules/cjs/loader.js:1072:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) at Module.load (internal/modules/cjs/loader.js:937:32) at Function.Module._load (internal/modules/cjs/loader.js:778:12) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at doRegisterPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:337:39) { code: 'ERR_PACKAGE_PATH_NOT_EXPORTED' }
Apr 21 22:51:42 signalk-server running at 0.0.0.0:3000
Apr 21 22:51:42 (node:1367) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023. Please migrate your code to use AWS SDK for JavaScript (v3). For more information, check the migration guide at https://a.co/7PzMCcy (Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by seamaster101** [comment]
Found the fix:
run npm install uuid@^3.3.2 --save-dev
this fixes the problem
